### ISSUE TITLE
3.4.0 breaks babel-eslint

### ISSUE THREAD

**Issue by keithamus** [estools/escope#99] opened 2016-02-01 17:18 UTC
Hey, thanks for making a great project!

Sadly, it looks like `3.4.0` broke eslint with babel-eslint:

```bash
$ npm ls escope
mypackage@0.0.0-development /<snip>/mypackage
└── escope@3.3.0

$ grep eslintConfig -A6 package.json
  "eslintConfig": {
    "extends": "strict",
    "parser": "babel-eslint",
    "rules": {
      "spaced-comment": 0
    }
  },

$ eslint .
 # no errors

$ npm i escope@3.4.0

$ eslint .
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/<snip>/myproject/node_modules/babel-eslint/index.js:220:40)
    at Object.exports.parse (/<snip>/myproject/node_modules/babel-eslint/index.js:362:5)
    at parse (/<snip>/myproject/node_modules/eslint/lib/eslint.js:512:27)
    at EventEmitter.module.exports.api.verify (/<snip>/myproject/node_modules/eslint/lib/eslint.js:646:19)
    at processText (/<snip>/myproject/node_modules/eslint/lib/cli-engine.js:230:27)
    at processFile (/<snip>/myproject/node_modules/eslint/lib/cli-engine.js:270:18)
    at executeOnFile (/<snip>/myproject/node_modules/eslint/lib/cli-engine.js:617:23)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/<snip>/myproject/node_modules/eslint/lib/cli-engine.js:640:56)
    at Object.cli.execute (/<snip>/myproject/node_modules/eslint/lib/cli.js:162:95)
```

**Comment by keithamus** [comment] 2016-02-01 17:19
If you'd like me to make a reduced test case, I can do so. Let me know if you'd like anything else from me too.

**Comment by bluejamesbond** [comment] 2016-02-01 17:32
+1

**Comment by nihey** [comment] 2016-02-01 17:42
+1

**Comment by djMax** [comment] 2016-02-01 17:50
+1

**Comment by mitchhentges** [comment] 2016-02-01 18:20
+1

**Comment by jmeline** [comment] 2016-02-01 18:37
+1

**Comment by michaelficarra** [comment] 2016-02-01 18:48
Strange, there's only been one nontrivial commit since 3.3 (https://github.com/estools/escope/commit/17f56889e202e1453f40a7ca669b42b8e801d62f). @nre?

**Comment by tony99nyr** [comment] 2016-02-01 19:03
Yeah this is a complete blocker for us.  +1

**Comment by nre** [comment] 2016-02-01 19:18
@michaelficarra
I haven't been using babel-eslint, but I'll try and work out what's gone wrong.

**Comment by adamlevasseur** [comment] 2016-02-01 19:28
+1

**Comment by hzoo** [comment] 2016-02-01 19:35
Just saw this now. It's the babel 6 update - Just need to update the require statements (https://github.com/babel/babel-eslint/pull/244) everyone can follow https://github.com/babel/babel-eslint/issues/243

**Comment by nre** [comment] 2016-02-01 19:39
@michaelficarra 

The transpiled file `lib/referencer.js` looks completely different in v3.3 and v3.4. Here is `visitClass` in v3.3:
```js
visitClass: {
    value: function visitClass(node) {
        if (node.type === Syntax.ClassDeclaration) {
            this.currentScope().__define(node.id, new Definition(Variable.ClassName, node.id, node, null, null, null));
        }

        // FIXME: Maybe consider TDZ.
        this.visit(node.superClass);

        this.scopeManager.__nestClassScope(node);

        if (node.id) {
            this.currentScope().__define(node.id, new Definition(Variable.ClassName, node.id, node));
        }
        this.visit(node.body);

        this.close(node);
    }
},
```
And this is why it can't be found in v3.4:
```js
}, {
    key: 'visitClass',
    value: function visitClass(node) {
        if (node.type === _estraverse.Syntax.ClassDeclaration) {
            this.currentScope().__define(node.id, new _definition.Definition(_variable2.default.ClassName, node.id, node, null, null, null));
        }

        // FIXME: Maybe consider TDZ.
        this.visit(node.superClass);

        this.scopeManager.__nestClassScope(node);

        if (node.id) {
            this.currentScope().__define(node.id, new _definition.Definition(_variable2.default.ClassName, node.id, node));
        }
        this.visit(node.body);

        this.close(node);
    }
}, {
```

**Comment by dysfunc** [comment] 2016-02-01 19:40
+1

**Comment by michaelficarra** [comment] 2016-02-01 19:42
@nre Don't bother.

Closing, as this is certainly a problem with the hacky way babel-eslint is trying to monkeypatch escope. If they're doing that, they should be responsible and lock the version down.

**Closed by michaelficarra** 2016-02-01 19:42 UTC

**Comment by hzoo** [comment] 2016-02-01 19:45
@michaelficarra yeah it's definitely something that needs to be updated in babel-eslint. Also we can lock the escope version since babel-eslint doesn't have escope as a dependency (it's using the one in eslint).

**Comment by kittens** [comment] 2016-02-01 20:31
@michaelficarra The monkeypatching is only necessary because ESLint and Escope lack any extension APIs.

**Comment by nzakas** [comment] 2016-02-01 20:39
Let's be clear for anyone else that might come across this issue: the `parser` configuration for ESLint was intended for modules that look like Esprima and would produce an ESTree-compatible tree. What babel-eslint is doing, reaching up into ESLint's dependencies, is far beyond the scope of what was intended and is definitely a void-your-warranty situation. 

@kittens I previously [asked you for feedback](https://phabricator.babeljs.io/T1829#53991) on how to make ESLint more pluggable so we could avoid such hacks and didn't hear anything back. In the meantime, @hzoo and I have been discussing some options here: https://github.com/eslint/eslint/issues/4640.

**Comment by kittens** [comment] 2016-02-01 21:16
@nzakas Yeah I know, I really appreciate your cooperation. I was just giving some historical context. I don't work on `babel-eslint` and have stepped away from Babel core mostly so I lack the time and oversight to make any useful suggestions.

**Comment by nzakas** [comment] 2016-02-01 21:39
@kittens no worries, @hzoo and I will be continue plugging along to see if we can figure out something useful.

**Comment by alexeyraspopov** [comment] 2016-02-02 18:32
Okay, now we have both babel/babel-eslint#243, estools/escope#99 closed and no solution. Where and how it can be fixed? Users in real world are suffering from broken things

**Comment by nre** [comment] 2016-02-02 20:27
From babel/babel-eslint#243:
    
    This is fixed in the latest 2 versions (update your babel-eslint).
    
    npm i babel-eslint will be >= 4.1.7.
    Use npm install --save-dev babel-eslint@next or npm
      i babel-eslint@5.0.0-beta9
    
    On 02/02/2016 18:32, Alexey Raspopov
      wrote:
    
    
      Okay, now we have both babel/babel-eslint#243,
        estools/escope#99
        closed and no solution. Where and how it can be fixed? Users in
        real world are suffering from broken things
      —
        Reply to this email directly or view
          it on GitHub.
